#pragma once

const int WINDOW_WIDTH = 1000;	// ekrano plotis
const int WINDOW_HEIGHT = 1000;	// ekrano aukstis
const int GROUND_LEVEL = 755; // zemes aukstis
const int JUMP_HEIGHT = 140; // sokio aukstis
const int MAP_WIDTH = 4850;
const int LUCKYBOX_FIRST_POSITION_X = 1120;
const int LUCKYBOX_FIRST_POSITION_Y = 655;
const int LUCKYBOX_NEW_POSITION = 1600;
const int FIRST_PLAYER_POSITION = 0;
const int MUSHROOM_POSITION_BIAS = 300;
const int RECT_LEFT = 80;
const int RECT_TOP = 0;
const int RECT_WIDTH = 70;
const int RECT_HEIGHT = 70;
const int MENU_SHIFT = 300;
const int MENU_FIRST_POSITION = 100;
const int FRAMERATE_LIMIT = 60;
const int TEXT_SHIFT = 140;
const int TEXT_Y_POSITION = 50;
const int ESCAPE_SHIFT_BY_X = 150;
const int ESCAPE_SHIFT_BY_Y = 100;
const int COIN_VECTOR_SIZE = 3;
const float ANIMATION_SHIFT = 0.12f;
const int FALLING_SPEED = 2;
const int ANIMATION_FRAMES_COUNT = 9;
const float MUSHROOM_MOVEMENT_SPEED = 1.5f;
const int FONT_SIZE = 80;
const int FONT_OUTLINE_THICKNESS = 3;
const int COIN_MAX_RANDOM_COUNT = 5;
const int GLOBAL_MOVEMENT_SPEED = 5;
const int OBJECT_INIT_POSITION = 0;